spring:
  application:
    name: mcp
  config:
    import: optional:file:.env[.properties]
  ai:
    mcp:
      server:
        name: news-server
        type: SYNC
        annotation-scanner:
          enabled: true
        protocol: SSE
        stdio: false
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo

news:
  rss:
    sources:
      yonhap:
        name: "연합뉴스"
        url: "https://www.yna.co.kr/rss/"
        enabled: true
        categories:
          economy: "economy.xml"
          politics: "politics.xml"
          all: "news.xml"
      hankyung:
        name: "한국경제"
        url: "https://www.hankyung.com/feed/"
        enabled: true
        categories:
          economy: "economy"
          politics: "politics"
          all: "all-news"
      mk:
        name: "매일경제"
        url: "https://www.mk.co.kr/rss/"
        enabled: true
        categories:
          economy: "30100041"
          politics: "30200030"
          all: "40300001"


management:
  endpoints:
    web:
      exposure:
        include: mappings, health

